# ========================
# General Spring Settings
# ========================
spring.application.name=auth-service
server.port=8081

# ========================
# Logging (Optional)
# ========================
logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=INFO

# ========================
# Keycloak Config
# ========================
keycloak.server-url=http://localhost:31337
keycloak.realm=foodcart-realm
keycloak.client-id=auth-service
keycloak.client-secret=NQu5com75VWbzc3evONWsvcPAdMCL0DQ
keycloak.admin-username=admin
keycloak.admin-password=admin
keycloak.grant-type=password

# ========================
# OAuth2 Resource Server JWT
# ========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

# ========================
# Swagger/OpenAPI Config (Optional)
# ========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
