apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432           # Internal Cluster Port
      targetPort: 5432     # Container Port
      nodePort: 30032      # External Port on host (must be between 30000-32767)
